### ISSUE TITLE
[Docs] Add user-data flag

### ISSUE THREAD

**Issue by jdbohrman** [cherryservers/cherryctl#2]
Hello, I'm trying to work with `cherryctl` with user data but I can't seem to find the flag in the docs.

**Comment by ArturasRa** [comment]
Hello, you may use internal help of the binary itself for flags help:

`cherryctl add server`

> Usage:
>   cherry-cloud-cli add server [flags]
> 
> Flags:
>   -h, --help                   help for server
>   -s, --hostname string        Provide hostname (default "server-name.examples.com")
>   -i, --image string           Provide image
>   -d, --ip-addresses strings   Provide ip-addresses
>   -l, --plan-id string         Provide plan-id
>   -p, --project-id string      Provide project-id
>   -g, --region string          Provide region (default "EU-East-1")
>   -k, --ssh-keys strings       Provide ssh-keys
>       --tags stringToString    Provide key/value for tags: env=prod,name=node1 (default [])
>   -u, --user-data string       Provide blob of user-data in base64
> 

As you can see you may use -u flag to provide user-data. At the following URL you may find instructions on how to generate base64 blob for your script: [HERE](https://docs.cherryservers.com/knowledge/cloud-init-service)

In any case the I will add examples to README later on.
