### ISSUE TITLE
[RFE] get ipmi credentials for baremetal servers

### ISSUE THREAD

**Issue by pfeifferj** [cherryservers/cherryctl#30]
# Feature request

It would be really useful to be able to get ipmi console credentials along with the other metadata using `cherryctl get server -oyaml`

This would allow more advanced scripting/automation when provisioning bare metal servers. 

My specific use-case is related to [installer provisioned infrastructure (IPI) ](https://github.com/openshift/installer/blob/master/docs/user/metal/install_ipi.md#install-config). It would be really cool, if an end-user could spin up a cluster on your platform with practically zero need for intervention.

**Comment by zalmarge** [comment]
I like the idea, someone will most probably start working on it in the coming weeks. There will be constraints though.

IIRC we store IPMI (and OS) credentials for 24 hours or so to display it in the portal. Passwords are scrubbed after that, so `cherryctl server get -o yaml` would only work for that period of time. I also believe we would not be able to display passwords at the time of `cherryctl server create -o yaml` too, as passwords are created and set asynchronously, but I should check that.

**Comment by pfeifferj** [comment]
I think those constraints should still be fine for this use-case. The basic MVP process I have in mind would involve provisioning the machines and once complete creating a dynamic inventory and install-config.

**Comment by pfeifferj** [comment]
amazing! thank you @zalmarge
