### ISSUE TITLE
No login/password info for VPS after install

### ISSUE THREAD

**Issue by zalmarge** [cherryservers/cherryctl#38]
Once deployed, login and password for the server is stored in a system for 24 hours. Public API returns it and so should `cherryctl server get ID -o yaml`, but at least for VPS servers it doesn't.

**Comment by caliban0** [comment]
I can't seem to replicate this. When I create a VPS and use ```cherryctl server get ID -o json | jq '{username: .username, password: .password}'``` or the YAML equivalent, I get the username "root" as well as the password.

**Comment by zalmarge** [comment]
You're right. Tracked down to the issue in VPS backend. Closing the issue. Thanks!
